export const australianCarData = [
    { make: 'Abarth', models: ['124', '500', '595', '695'] },
    {
      make: 'Alfa Romeo',
      models: [
        '147',
        '156',
        '159',
        '164',
        '166',
        '1300',
        '1600',
        '1750',
        '2000',
        '2600',
        '4C',
        'Alfa 33',
        'Alfa 75',
        'Alfa 90',
        'Alfasud',
        'Alfetta',
        'Brera',
        'Giulia',
        'Giulietta',
        'GT',
        'GTV',
        'MiTo',
        'Montreal',
        'Spider',
        'Sprint',
        'Stelvio',
      ],
    },
    { make: 'Alpina', models: ['B3', 'B4', 'B5', 'B7', 'C2', 'XD3'] },
    { make: 'Alpine', models: ['A110'] },
    { make: 'Armstrong Siddeley', models: ['Star Sapphire'] },
    { make: 'Asia Motors', models: ['Rocsta'] },
    {
      make: 'Aston Martin',
      models: [
        'DB11',
        'DB4',
        'DB5',
        'DB6',
        'DB7',
        'DB9',
        'DBS',
        'Lagonda',
        'Rapide',
        'V12',
        'V8',
        'Vanquish',
        'Vantage',
        'Virage',
      ],
    },
    {
      make: 'Audi',
      models: [
        '80',
        '90',
        '100',
        '200T',
        '5+5',
        '5E',
        '80 CC',
        'A1',
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
        'A8',
        'allroad',
        'Cabriolet',
        'Fox',
        'Q2',
        'Q3',
        'Q5',
        'Q7',
        'Q8',
        'R8',
        'RS Q3',
        'RS3',
        'RS4',
        'RS5',
        'RS6',
        'RS7',
        'S1',
        'S2',
        'S3',
        'S4',
        'S5',
        'S6',
        'S7',
        'S8',
        'SQ5',
        'SQ7',
        'Super 90',
        'TT',
        'TT RS',
        'TTS',
        'V8',
      ],
    },
    {
      make: 'Austin',
      models: [
        '1800',
        'A/40',
        'Cambridge',
        'Freeway',
        'Lancer',
        'Westminster',
        'X6',
      ],
    },
    { make: 'Austin Healey', models: ['3000', 'Sprite'] },
    { make: 'Australian Classic Car', models: ['TD 2000'] },
    { make: 'Bedford', models: ['CFL', 'CFS', 'TJ'] },
    {
      make: 'Bentley',
      models: [
        'Arnage',
        'Azure',
        'Bentayga',
        'Brooklands',
        'Continental',
        'Corniche',
        'Eight',
        'Flying Spur',
        'Mulsanne',
        'S Type',
        'T',
        'T2',
        'Turbo',
      ],
    },
    { make: 'Bertone', models: ['X1/9'] },
    { make: 'Blade', models: ['Electron'] },
    { make: 'BMC', models: ['Gipsy'] },
    {
      make: 'BMW',
      models: [
        '3',
        '1600',
        '1602',
        '1800',
        '2000',
        '2002',
        '2500',
        '2800',
        '1 Series',
        '1 Series M',
        '2 Series',
        '3 Series',
        '3.3L',
        '4 Series',
        '5 Series',
        '6 Series',
        '7 Series',
        '8 Series',
        'i3',
        'i8',
        'M',
        'M2',
        'M3',
        'M4',
        'M5',
        'M6',
        'X1',
        'X2',
        'X3',
        'X3 M',
        'X4',
        'X4 M',
        'X5',
        'X5 M',
        'X6',
        'X6 M',
        'X7',
        'Z3',
        'Z4',
        'Z4 M',
      ],
    },
    { make: 'Bolwell', models: ['Mk VII', 'Nagari'] },
    { make: 'Bufori', models: ['MK I', 'MK II'] },
    { make: 'Bugatti', models: ['EB110'] },
    { make: 'Buick', models: ['Electra', 'Riviera'] },
    { make: 'Cadillac', models: ['De Ville', 'Eldorado', 'Seville'] },
    { make: 'Caterham', models: ['7', 'Super 7'] },
    { make: 'Chery', models: ['J1', 'J11', 'J3'] },
    {
      make: 'Chevrolet',
      models: [
        'Bel Air',
        'C20',
        'C30',
        'Camaro',
        'Corvette',
        'Impala',
        'K30',
        'Silverado',
      ],
    },
    {
      make: 'Chrysler',
      models: [
        '300',
        '300c',
        'Centura',
        'Chrysler',
        'Crossfire',
        'Dodge',
        'Galant',
        'Grand Voyager',
        'Lancer',
        'Neon',
        'PT Cruiser',
        'Royal',
        'Sebring',
        'Sigma',
        'V.I.P.',
        'Valiant',
        'Valiant Charger',
        'Valiant Regal',
        'Viper',
        'Voyager',
        'Wayfarer',
      ],
    },
    {
      make: 'Citroen',
      models: [
        'AX',
        'Berlingo',
        'BX',
        'C2',
        'C3',
        'C3 Aircross',
        'C4',
        'C4 Aircross',
        'C4 Cactus',
        'C4 Picasso',
        'C5',
        'C5 Aircross',
        'C6',
        'CX2200',
        'CX2400',
        'CX2500',
        'D',
        'Dispatch',
        'DS-21',
        'DS-23',
        'DS3',
        'DS4',
        'DS5',
        'G',
        'Grand C4 Picasso',
        'GS',
        'ID-19',
        'Xantia',
        'XM',
        'Xsara',
      ],
    },
    { make: 'Commer', models: ['1500', '2500'] },
    {
      make: 'CSV',
      models: ['Bullet', 'La Classe', 'Mondo', 'Strada', 'Veloce', 'Volanti'],
    },
    {
      make: 'Daewoo',
      models: [
        '1.5i',
        'Cielo',
        'Espero',
        'Kalos',
        'Korando',
        'Lacetti',
        'Lanos',
        'Leganza',
        'Matiz',
        'Musso',
        'Nubira',
        'Tacuma',
      ],
    },
    {
      make: 'Daihatsu',
      models: [
        '800',
        '1000',
        '360X',
        'Applause',
        'Charade',
        'Charade Centro',
        'Compagno',
        'Copen',
        'Cuore',
        'F10L',
        'F20JK',
        'F20JT',
        'F20JV',
        'F20LV',
        'F25P',
        'Feroza',
        'Feroza II',
        'Handi',
        'Handivan',
        'Hi – Jet',
        'Mira',
        'Move',
        'Pyzar',
        'Rocky',
        'S38V',
        'S40V',
        'S60V',
        'S65V',
        'Scat',
        'Sirion',
        'Terios',
        'YRV',
      ],
    },
    {
      make: 'Daimler',
      models: [
        '250',
        '2.5LT',
        '3.6 Litre',
        '4 Litre',
        'Double 6',
        'Six',
        'Sovereign',
        'SP250',
        'Super V8',
        'V8',
      ],
    },
    {
      make: 'Datsun',
      models: [
        '620',
        '1000',
        '1200',
        '1600',
        '2000',
        '2300',
        '2400',
        '120Y',
        '1600 Sports',
        '180B',
        '2000 Sports',
        '2000-GT',
        '200B',
        '240C',
        '240K',
        '240Z',
        '260C',
        '260Z',
        '280C',
        '280ZX',
        'Bluebird',
        'E20',
        'Fairlady',
        'Patrol',
        'Silvia',
        'Skyline',
        'Stanza',
        'Sunny',
      ],
    },
    {
      make: 'De Tomaso',
      models: ['Deauville', 'Longchamp', 'Pantera', 'Spider'],
    },
    {
      make: 'Dodge',
      models: ['Avenger', 'Caliber', 'Journey', 'Nitro', 'Phoenix'],
    },
    {
      make: 'Elfin',
      models: ['MS8 Clubman', 'MS8 Streamliner', 'TYPE 3', 'Type 5'],
    },
    { make: 'Eunos', models: ['500', '800', '30X'] },
    {
      make: 'Ferrari',
      models: [
        '308',
        '328',
        '330',
        '348',
        '360',
        '365',
        '456',
        '512',
        '456M',
        '458 Italia',
        '458 Speciale',
        '458 Spider',
        '488 GTB',
        '488 Pista',
        '488 Pista Spider',
        '488 Spider',
        '512tr',
        '550 Maranello',
        '575 Maranello',
        '599 Fiorano',
        '612 Scaglietti',
        '812 Superfast',
        'California',
        'Dino',
        'F12berlinetta',
        'F12tdf',
        'F355',
        'F430',
        'F50',
        'F512M',
        'FF',
        'GTC4Lusso',
        'Mondial',
        'Portofino',
        'Scuderia',
        'Superamerica',
      ],
    },
    {
      make: 'Fiat',
      models: [
        '124',
        '125',
        '127',
        '128',
        '130',
        '131',
        '132',
        '500',
        '600',
        '770',
        '850',
        '1100',
        '1500',
        '1800',
        '2100',
        '2300',
        '500C',
        '500X',
        'Argenta',
        'Croma',
        'Doblo',
        'Ducato',
        'Freemont',
        'Panda',
        'Punto',
        'Regata',
        'Ritmo',
        'Scudo',
        'Superbrava',
        'X1/9',
      ],
    },
    {
      make: 'Ford',
      models: [
        'Anglia',
        'Bronco',
        'Capri',
        'Consul',
        'Consul – Cortina',
        'Corsair',
        'Cortina',
        'Cougar',
        'Courier',
        'Custom',
        'Econovan',
        'EcoSport',
        'Endura',
        'Escape',
        'Escort',
        'Everest',
        'Explorer',
        'F100',
        'F150',
        'F250',
        'F350',
        'Fairlane',
        'Fairmont',
        'Falcon',
        'Falcon Ute',
        'Festiva',
        'Fiesta',
        'Focus',
        'Galaxie',
        'Ka',
        'Kuga',
        'Landau',
        'Laser',
        'LTD',
        'Maverick',
        'Meteor',
        'Mondeo',
        'Mustang',
        'Prefect 105E',
        'Probe',
        'Raider',
        'Ranger',
        'Spectron',
        'Taurus',
        'TE50',
        'Telstar',
        'Telstar TX5',
        'Territory',
        'Thunderbird',
        'TL50',
        'Transit',
        'Transit Custom',
        'TS50',
        'Zephyr',
      ],
    },
    {
      make: 'Ford Performance Vehicles',
      models: [
        'F6',
        'F6 E',
        'F6 Tornado',
        'F6 Typhoon',
        'F6X',
        'Force 6',
        'Force 8',
        'GS',
        'GT',
        'GT F',
        'GT-E',
        'GT-P',
        'Pursuit',
        'Super Pursuit',
      ],
    },
    { make: 'Foton', models: ['Sauvana', 'Tunland', 'View'] },
    { make: 'FSM', models: ['Niki'] },
    { make: 'Geely', models: ['MK'] },
    { make: 'Genesis', models: ['G70', 'G80'] },
    { make: 'Giocattolo', models: ['Group B'] },
    {
      make: 'Great Wall',
      models: ['H6', 'SA220', 'Steed', 'V200', 'V240', 'X200', 'X240'],
    },
    { make: 'Haval', models: ['H2', 'H6', 'H8', 'H9'] },
    { make: 'HDT', models: ['VC Retro', 'VH Retro'] },
    {
      make: 'Hillman',
      models: [
        'Arrow',
        'Gazelle',
        'Hunter',
        'Husky',
        'Imp',
        'Minx',
        'Super Minx',
      ],
    },
    { make: 'Hino', models: ['Contessa'] },
    {
      make: 'Holden',
      models: [
        'Acadia',
        'Adventra',
        'Apollo',
        'Astra',
        'Barina',
        'Barina Spark',
        'Belmont',
        'Berlina',
        'Brock',
        'Brougham',
        'Calais',
        'Calibra',
        'Camira',
        'Caprice',
        'Captiva',
        'Cascada',
        'Chev Luv',
        'Colorado',
        'Colorado 7',
        'Combo',
        'Commodore',
        'Crewman',
        'Cruze',
        'Drover',
        'EH',
        'EJ',
        'EK',
        'Epica',
        'Equinox',
        'FB',
        'Frontera',
        'Gemini',
        'HD',
        'HR',
        'Insignia',
        'Isuzu',
        'Jackaroo',
        'Kingswood',
        'Malibu',
        'Monaro',
        'Monterey',
        'Nova',
        'One tonner',
        'Piazza',
        'Premier',
        'Rodeo',
        'Sandman',
        'Scurry',
        'Shuttle',
        'Spark',
        'SS',
        'Statesman',
        'Suburban',
        'Sunbird',
        'Tigra',
        'Torana',
        'Trailblazer',
        'Trax',
        'Ute',
        'Vectra',
        'VG',
        'Viva',
        'Volt',
        'WB',
        'Zafira',
      ],
    },
    {
      make: 'Holden Special Vehicles',
      models: [
        'Astra sv1800',
        'Avalanche',
        'Calais',
        'Caprice',
        'Clubsport',
        'Colorado',
        'Commodore',
        'Coupe',
        'Grange',
        'GTS',
        'Jackaroo',
        'LS',
        'Maloo',
        'Manta',
        'Nitron',
        'Senator',
        'Sport',
        'Statesman',
        'SV Clubsport',
        'SV300',
        'SV6000',
        'SV91',
        'SV99',
        'VXR',
        'W427',
        'XU6',
        'XU8',
      ],
    },
    {
      make: 'Honda',
      models: [
        '1300',
        'Accord',
        'Accord Euro',
        'Acty',
        'Beat',
        'City',
        'Civic',
        'Concerto',
        'CR-V',
        'CRX',
        'CR-Z',
        'HR-V',
        'Insight',
        'Integra',
        'Jazz',
        'Legend',
        'Life',
        'MDX',
        'N600',
        'NSX',
        'Odyssey',
        'Prelude',
        'S2000',
        'S600',
        'S800',
        'Scamp',
        'Z360',
      ],
    },
    { make: 'Humber', models: ['Hawk', 'Super Snipe', 'Vogue'] },
    { make: 'Hummer', models: ['H3'] },
    {
      make: 'Hyundai',
      models: [
        'Accent',
        'Coupe',
        'Elantra',
        'Elantra LaVita',
        'Excel',
        'Genesis',
        'Getz',
        'Grandeur',
        'i20',
        'i30',
        'i40',
        'i45',
        'iLoad',
        'iMax',
        'IONIQ',
        'ix35',
        'Kona',
        'Lantra',
        'S Coupe',
        'Santa Fe',
        'Sonata',
        'Terracan',
        'Tiburon',
        'Trajet',
        'Tucson',
        'Veloster',
        'Venue',
      ],
    },
    {
      make: 'INFINITI',
      models: [
        'FX30d',
        'FX37',
        'FX50',
        'G37',
        'M30d',
        'M35h',
        'M37',
        'Q30',
        'Q50',
        'Q60',
        'Q70',
        'QX30',
        'QX70',
        'QX80',
      ],
    },
    { make: 'International', models: ['Scout'] },
    { make: 'ISO', models: ['Fidia', 'Grifo', 'Lele', 'Rivolta'] },
    {
      make: 'Isuzu',
      models: [
        'Bellet',
        'D-MAX',
        'Florian',
        'Gemini',
        'MU',
        'MU-X',
        'Piazza',
        'Vehicross',
      ],
    },
    {
      make: 'Jaguar',
      models: [
        '240',
        '340',
        '420',
        '420G',
        'E Type',
        'E-PACE',
        'F-PACE',
        'F-TYPE',
        'I-PACE',
        'Mark II',
        'Mark IX',
        'Mark X',
        'S Type',
        'Sovereign',
        'S-Type',
        'Super V8',
        'V12',
        'XE',
        'XF',
        'XJ',
        'XJ12',
        'XJ4.2',
        'XJ5.3',
        'XJ6',
        'XJ8',
        'XJR',
        'XJS',
        'XJ-SC',
        'XK',
        'XK150',
        'XK8',
        'XKR',
        'X-Type',
      ],
    },
    {
      make: 'Jeep',
      models: [
        'Cherokee',
        'CJ5',
        'CJ6',
        'CJ7',
        'CJ8',
        'Commander',
        'Compass',
        'Grand Cherokee',
        'J10',
        'J20',
        'Patriot',
        'Renegade',
        'Wrangler',
      ],
    },
    { make: 'Jensen', models: ['Healey', 'Interceptor'] },
    { make: 'JMC', models: ['Vigus'] },
    {
      make: 'Kia',
      models: [
        'Carens',
        'Carnival',
        'Cerato',
        'Ceres',
        'Credos',
        'Grand Carnival',
        'K2700',
        'K2900',
        'Magentis',
        'Mentor',
        'Optima',
        'Picanto',
        'Pregio',
        'pro_cee’d',
        'Rio',
        'Rondo',
        'Seltos',
        'Shuma',
        'Sorento',
        'Soul',
        'Spectra',
        'Sportage',
        'Stinger',
      ],
    },
    { make: 'KTM', models: ['X-BOW'] },
    {
      make: 'Lada',
      models: ['1300', 'Bizivan', 'Cevaro', 'Niva', 'Sable', 'Samara', 'Volante'],
    },
    {
      make: 'Lamborghini',
      models: [
        'Aventador',
        'Countach',
        'Diablo',
        'Gallardo',
        'Huracan',
        'Jalpa',
        'Murcielago',
        'Urraco',
        'Urus',
      ],
    },
    { make: 'Lancia', models: ['Beta', 'Flaminia', 'Flavia', 'Fulvia'] },
    {
      make: 'Land Rover',
      models: [
        '110',
        'Defender',
        'Discovery',
        'Discovery 3',
        'Discovery 4',
        'Discovery Sport',
        'Freelander',
        'Freelander 2',
        'Range Rover',
        'Range Rover Evoque',
        'Range Rover Sport',
        'Range Rover Velar',
        'Range Rover Vogue',
        'Rover',
      ],
    },
    { make: 'LDV', models: ['D90', 'G10', 'T60', 'V80'] },
    {
      make: 'Lexus',
      models: [
        'CT',
        'ES',
        'GS',
        'IS',
        'LC',
        'LFA',
        'LS',
        'LX',
        'NX',
        'RC',
        'RX',
        'SC',
        'UX',
      ],
    },
    { make: 'Leyland', models: ['Marina', 'Mini', 'Moke', 'P76'] },
    { make: 'Lightburn', models: ['Zeta'] },
    { make: 'Lincoln', models: ['Mark VIII'] },
    {
      make: 'Lotus',
      models: [
        'Eclat',
        'Elan',
        'Elise',
        'Elite',
        'Esprit',
        'Europa',
        'Evora',
        'Excel',
        'Exige',
      ],
    },
    {
      make: 'Mahindra',
      models: ['Bushranger', 'Genio', 'PIK-UP', 'Stockman', 'XUV500'],
    },
    {
      make: 'Maserati',
      models: [
        '222',
        '228',
        '430',
        '3200GT',
        'Biturbo',
        'Coupe',
        'Ghibli',
        'GranCabrio',
        'Gransport',
        'GranTurismo',
        'Karif',
        'Khamsin',
        'Kyalami',
        'Levante',
        'Merak',
        'Quattroporte',
        'Shamal',
        'Spyder',
      ],
    },
    { make: 'Maybach', models: ['57', '62'] },
    {
      make: 'Mazda',
      models: [
        '2',
        '3',
        '6',
        '121',
        '323',
        '600',
        '626',
        '800',
        '808',
        '929',
        '1000',
        '1200',
        '1300',
        '1500',
        '1800',
        '121L',
        '929l',
        'B1500',
        'B1600',
        'B1800',
        'B2000',
        'B2200',
        'B2600',
        'Bongo',
        'Bravo',
        'BT-50',
        'Capella',
        'Capella RX-2',
        'Cosmo',
        'CX-3',
        'CX-30',
        'CX-5',
        'CX-7',
        'CX-8',
        'CX-9',
        'E1300',
        'E1400',
        'E1600',
        'E1800',
        'E2000',
        'E2200',
        'E2500',
        'Eunos 30X',
        'Eunos 500',
        'Eunos 800',
        'Familia',
        'Millenia',
        'MPV',
        'MX-5',
        'MX-6',
        'Premacy',
        'R100',
        'RX-3',
        'RX-4',
        'RX-5',
        'RX-7',
        'RX-8',
        'Tribute',
      ],
    },
    {
      make: 'McLaren',
      models: [
        '540C',
        '570GT',
        '570S',
        '600LT',
        '650S',
        '675LT',
        '720S',
        'MP4-12C',
      ],
    },
    {
      make: 'Mercedes-Benz',
      models: [
        '190',
        '200',
        '220',
        '230',
        '250',
        '280',
        '600',
        '180E',
        '190B',
        '190C',
        '190D',
        '190DB',
        '190DC',
        '190E',
        '190SL',
        '200D',
        '220D',
        '220E',
        '220S',
        '220SE',
        '230E',
        '230GE',
        '230S',
        '230SL',
        '230TE',
        '240D',
        '250C',
        '250CE',
        '250S',
        '250SE',
        '250SL',
        '260E',
        '280CE',
        '280E',
        '280S',
        '280SE',
        '280SEL',
        '280SL',
        '280SLC',
        '280TE',
        '300CE',
        '300CE-24',
        '300D',
        '300E',
        '300GD',
        '300SE',
        '300SEL',
        '300SL',
        '300TD',
        '300TE',
        '320CE',
        '320E',
        '350SE',
        '350SEL',
        '350SL',
        '350SLC',
        '380SE',
        '380SEC',
        '380SEL',
        '380SL',
        '400SE',
        '400SEL',
        '420SE',
        '420SEL',
        '450SE',
        '450SEL',
        '450SL',
        '450SLC',
        '500SEC',
        '500SEL',
        '500SL',
        '560SEC',
        '560SEL',
        '560SL',
        '600SEL',
        '600SL',
        'A-Class',
        'AMG GT',
        'B-Class',
        'C-Class',
        'CLA-Class',
        'CLC-Class',
        'CL-Class',
        'CLK-Class',
        'CLS-Class',
        'E-Class',
        'EQC',
        'G-Class',
        'GLA-Class',
        'GLC-Class',
        'GL-Class',
        'GLE-Class',
        'GLS-Class',
        'Marco Polo ACTIVITY',
        'MB100',
        'MB140',
        'M-Class',
        'R-Class',
        'S-Class',
        'SLC-Class',
        'SL-Class',
        'SLK-Class',
        'SLS-Class',
        'Sprinter',
        'Valente',
        'V-Class',
        'Viano',
        'Vito',
        'X-Class',
      ],
    },
    {
      make: 'MG',
      models: [
        'A',
        'B',
        'F',
        'GS',
        'HS',
        'Magnette',
        'MG3',
        'MG6',
        'MG6 PLUS',
        'Midget',
        'TF',
        'ZR',
        'ZS',
        'ZT',
      ],
    },
    {
      make: 'MINI',
      models: [
        'Cabrio',
        'Clubman',
        'Convertible',
        'Countryman',
        'Coupe',
        'Hatch',
        'Paceman',
        'Roadster',
      ],
    },
    {
      make: 'Mitsubishi',
      models: [
        '380',
        '3000GT',
        'Airtrek',
        'ASX',
        'Challenger',
        'Colt',
        'Cordia',
        'D50 Express',
        'Delica',
        'Eclipse Cross',
        'Express',
        'FTO',
        'Galant',
        'Grandis',
        'GTO',
        'i-MiEV',
        'Lancer',
        'Legnum',
        'Magna',
        'Mirage',
        'Nimbus',
        'Outlander',
        'Pajero',
        'Pajero iO',
        'Pajero Sport',
        'Ralliart Evo',
        'Ralliart Magna',
        'RVR',
        'Sigma',
        'Sigma Scorpion',
        'Starion',
        'Starwagon',
        'Triton',
        'Verada',
      ],
    },
    {
      make: 'Morgan',
      models: [
        '43559',
        '3 Wheeler',
        'AERO',
        'AERO 8',
        'Plus 4',
        'PLUS 8',
        'Roadster',
        'Runabout',
      ],
    },
    {
      make: 'Morris',
      models: [
        '850',
        '1100',
        '1300',
        '1500',
        'Major',
        'Mini',
        'Mini Clubman',
        'Mini Cooper',
        'Minor',
        'Moke',
        'Oxford',
      ],
    },
    {
      make: 'Nissan',
      models: [
        '720',
        '1200',
        '180SX',
        '200B',
        '200SX',
        '280C',
        '280ZX',
        '300C',
        '300ZX',
        '350Z',
        '370Z',
        'Almera',
        'Altima',
        'Bluebird',
        'C20',
        'Cedric',
        'Cefiro',
        'Cube',
        'Dualis',
        'E20',
        'Elgrand',
        'Exa',
        'Gazelle',
        'GT-R',
        'Infiniti',
        'JUKE',
        'Largo',
        'LEAF',
        'Maxima',
        'Micra',
        'Murano',
        'Navara',
        'Nomad',
        'NX',
        'Pathfinder',
        'Patrol',
        'Pintara',
        'Prairie',
        'Pulsar',
        'QASHQAI',
        'S Cargo',
        'Serena',
        'Silvia',
        'Skyline',
        'Stagea',
        'Stanza',
        'Sunny',
        'Terrano II',
        'The Ute',
        'Tiida',
        'Urvan',
        'Vanette',
        'X-TRAIL',
      ],
    },
    { make: 'Noble', models: ['M12'] },
    { make: 'NSU', models: ['Prinz', 'Ro 80'] },
    { make: 'Opel', models: ['Astra', 'Corsa', 'Insignia', 'Zafira'] },
    { make: 'Pagani', models: ['Zonda'] },
    {
      make: 'Peugeot',
      models: [
        '205',
        '206',
        '207',
        '208',
        '306',
        '307',
        '308',
        '403',
        '404',
        '405',
        '406',
        '407',
        '504',
        '505',
        '508',
        '604',
        '605',
        '607',
        '2008',
        '3008',
        '4007',
        '4008',
        '5008',
        'Boxer',
        'Expert',
        'Partner',
        'RCZ',
      ],
    },
    { make: 'Pontiac', models: ['Firebird', 'Laurentian', 'Parisienne'] },
    {
      make: 'Porsche',
      models: [
        '718',
        '911',
        '912',
        '924',
        '928',
        '930',
        '944',
        '968',
        '356B',
        '356C',
        '356SC',
        'Boxster',
        'Cayenne',
        'Cayman',
        'Macan',
        'Panamera',
      ],
    },
    {
      make: 'Proton',
      models: [
        'Exora',
        'Gen 2',
        'Jumbuck',
        'M21',
        'Persona',
        'Preve',
        'S16',
        'Satria',
        'Savvy',
        'Suprima S',
        'Waja',
        'Wira',
      ],
    },
    { make: 'RAM', models: ['1500', '2500', '3500'] },
    {
      make: 'Rambler',
      models: [
        'American 330',
        'American 440',
        'AMX',
        'Classic',
        'Classic 660 V8',
        'Hornet',
        'Javelin',
        'Matador',
        'Rebel',
      ],
    },
    {
      make: 'Renault',
      models: [
        '1.4',
        '10',
        '12',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '750',
        'Captur',
        'Caravelle',
        'Clio',
        'Dauphine',
        'Floride',
        'Fluence',
        'Fuego',
        'Grand scenic',
        'Kadjar',
        'Kangoo',
        'Koleos',
        'Laguna',
        'Latitude',
        'Master',
        'Megane',
        'R25',
        'R4',
        'R8',
        'Scenic',
        'Scenic RX4',
        'Trafic',
        'Virage',
        'Zoe',
      ],
    },
    { make: 'Robnell', models: ['302SC', '429SC'] },
    {
      make: 'Rolls-Royce',
      models: [
        'Camargue',
        'Corniche',
        'Cullinan',
        'Dawn',
        'Flying Spur',
        'Ghost',
        'Park Ward',
        'Phantom',
        'Silver Cloud',
        'Silver Dawn',
        'Silver Seraph',
        'Silver Shadow',
        'Silver Spirit',
        'Silver Spur',
        'Wraith',
      ],
    },
    {
      make: 'Rover',
      models: [
        '75',
        '825',
        '827',
        '2000',
        '3500',
        '3 Litre',
        '3.5 LT',
        '416i',
        'Quintet',
      ],
    },
    { make: 'Saab', models: ['99', '900', '9000', '43711', '43713', '900i'] },
    { make: 'Seat', models: ['Cordoba', 'Ibiza', 'Toledo'] },
    { make: 'Simca', models: ['Aronde', 'Vedette'] },
    {
      make: 'SKODA',
      models: [
        '120L',
        'Fabia',
        'Karoq',
        'Kodiaq',
        'Octavia',
        'Rapid',
        'Roomster',
        'S100',
        'S110',
        'S120L',
        'Superb',
        'Yeti',
      ],
    },
    {
      make: 'smart',
      models: ['cabrio', 'city-coupe', 'forfour', 'fortwo', 'roadster'],
    },
    {
      make: 'SsangYong',
      models: [
        'Actyon',
        'Actyon Sports',
        'Chairman',
        'Korando',
        'Kyron',
        'Musso',
        'Rexton',
        'Stavic',
        'Tivoli',
        'Tivoli XLV',
      ],
    },
    { make: 'Studebaker', models: ['Hawk', 'Lark'] },
    {
      make: 'Subaru',
      models: [
        '1400',
        '1600',
        'Brumby',
        'BRZ',
        'Fiori',
        'Forester',
        'Impreza',
        'L Series',
        'Leone',
        'Levorg',
        'Liberty',
        'Outback',
        'Sherpa',
        'Sportswagon',
        'SVX',
        'Tribeca',
        'Vortex',
        'WRX',
        'XV',
      ],
    },
    {
      make: 'Suzuki',
      models: [
        'Alto',
        'APV',
        'Baleno',
        'Cappuccino',
        'Carry',
        'Celerio',
        'Cultus',
        'Grand Vitara',
        'Hatch',
        'Ignis',
        'Jimny',
        'Kizashi',
        'Liana',
        'LJ50',
        'LJ50V',
        'LJ80',
        'LJ80V',
        'LJ81K',
        'Mighty Boy',
        'S-Cross',
        'Sierra',
        'Swift',
        'SX4',
        'Vitara',
        'Wagon R+',
        'X-90',
        'XL-7',
      ],
    },
    { make: 'Tata', models: ['Safari', 'Telcoline', 'Xenon'] },
    { make: 'TD 2000', models: ['TD 2000'] },
    { make: 'Tesla', models: ['Model 3', 'Model S', 'Model X', 'Roadster'] },
    {
      make: 'Toyota',
      models: [
        '86',
        '700',
        '4Runner',
        'Aristo',
        'Aurion',
        'Avalon',
        'Avensis Verso',
        'Blizzard',
        'Caldina',
        'Camry',
        'Camry Vienta',
        'Carina',
        'Celica',
        'Chaser',
        'C-HR',
        'Corolla',
        'Corona',
        'Corona Avante',
        'Corsa',
        'Cressida',
        'Cresta',
        'Crown',
        'Cynos',
        'Echo',
        'Estima',
        'FJ Cruiser',
        'Fortuner',
        'Granvia',
        'Hiace',
        'Hiace SBV',
        'Hilux',
        'Hilux 4Runner',
        'Hilux Surf',
        'Kluger',
        'Landcruiser',
        'Landcruiser Prado',
        'Lexcen',
        'Liteace',
        'Mark II',
        'Masterace',
        'MR2',
        'Paseo',
        'Prius',
        'Prius C',
        'Prius V',
        'RAV4',
        'Rukus',
        'Sera',
        'Soarer',
        'Spacia',
        'Sprinter',
        'Starlet',
        'Stout',
        'Supra',
        'T-18',
        'Tarago',
        'Tercel',
        'Tiara',
        'Townace',
        'Vienta',
        'Yaris',
      ],
    },
    { make: 'TRD', models: ['Aurion', 'Hilux'] },
    {
      make: 'Triumph',
      models: [
        '2.5',
        '2000',
        '2500',
        '18598',
        'Dolomite',
        'GT6',
        'Herald',
        'Spitfire',
        'Stag',
        'TR3A',
        'TR4',
        'TR4A',
        'TR5',
        'TR6',
        'TR7',
      ],
    },
    { make: 'TVR', models: ['Chimaera', 'Griffith'] },
    { make: 'Vanden Plas', models: ['Princess', 'Princess 1100'] },
    {
      make: 'Vauxhall',
      models: ['Cresta', 'Velox', 'Victor', 'Viva', 'VX 4/90'],
    },
    {
      make: 'Volkswagen',
      models: [
        '1500',
        '1600',
        'Amarok',
        'Arteon',
        'Beetle',
        'Bora',
        'Caddy',
        'Caravelle',
        'CC',
        'Country',
        'Crafter',
        'Eos',
        'Golf',
        'Jetta',
        'Karmann Ghia',
        'Kombi',
        'Kombi Transporter',
        'LT',
        'Microbus',
        'Multivan',
        'Passat',
        'Polo',
        'Scirocco',
        'Superbug',
        'Tiguan',
        'Touareg',
        'Transporter',
        'up!',
        'Vento',
      ],
    },
    {
      make: 'Volvo',
      models: [
        '123',
        '124',
        '125',
        '142',
        '144',
        '145',
        '164',
        '240',
        '242',
        '244',
        '245',
        '262',
        '264',
        '265',
        '360',
        '440',
        '740',
        '760',
        '850',
        '940',
        '960',
        '122S',
        'C30',
        'C70',
        'Cross country',
        'P1800',
        'S40',
        'S60',
        'S70',
        'S80',
        'S90',
        'V40',
        'V40 Cross Country',
        'V50',
        'V60',
        'V60 Cross Country',
        'V70',
        'V90',
        'V90 Cross Country',
        'XC40',
        'XC60',
        'XC70',
        'XC90',
      ],
    },
    { make: 'Wolseley', models: ['36312', '15/60', '24/80', '6/110'] },
    { make: 'ZX Auto', models: ['Grand Tiger'] },
  ];