name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "apps/frontend/web/admin/**"
      - "package.json"
      - "yarn.lock"
  pull_request:
    branches: [main]
    paths:
      - "apps/frontend/web/admin/**"
      - "package.json"
      - "yarn.lock"

jobs:
  build-web:
    name: Build and Test Web App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Code
        run: yarn lint

      - name: TypeScript Check
        run: yarn tsc --build apps/frontend/web/admin/tsconfig.json

      - name: Build Web
        working-directory: apps/frontend/web/admin
        run: yarn build

      - name: Run Tests
        working-directory: apps/frontend/web/admin
        run: yarn test --coverage

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: apps/frontend/web/admin/.next

  # TODO: to be implemented once mobile app development has started 
  # build-mobile:
  #   name: Build Mobile App
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "yarn"

  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: TypeScript Check
  #       run: yarn tsc --build apps/frontend/mobile/tsconfig.json

  #     - name: Build Mobile
  #       working-directory: apps/frontend/mobile
  #       run: yarn build

  #     - name: Run Tests
  #       working-directory: apps/frontend/mobile
  #       run: yarn test
