version: '3.6'

services:
  redis:
    image: redis:5.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    volumes:
      - ./volumes/redis-data:/data
